version: '3.1'

services:
  backend:
    image: mathiask1/cookie-backend-app:latest
    ports: 
      - 9000:9000

  frontend:
    image: mathiask1/cookie-frontend-app:latest
    environment:
      - BACKEND_DNS=backend
    ports: 
      - 8080:8080
    depends_on:
     - backend